// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTXx4vic-brNpnc3g2MVZ9MI9U1r6QT4A',
    appId: '1:547375660208:web:8dbc241be464eaba890f75',
    messagingSenderId: '547375660208',
    projectId: 'flutter-maps-2408',
    authDomain: 'flutter-maps-2408.firebaseapp.com',
    storageBucket: 'flutter-maps-2408.firebasestorage.app',
    measurementId: 'G-P3222Z0PJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiGBhy-zasgyTCtQS5vsJ31xzJMGugOt0',
    appId: '1:547375660208:android:5503785a08831f17890f75',
    messagingSenderId: '547375660208',
    projectId: 'flutter-maps-2408',
    storageBucket: 'flutter-maps-2408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX_cVDWMqirYC276hPhrp3zYCqwXgCrzo',
    appId: '1:547375660208:ios:4cd72b05210f6ba4890f75',
    messagingSenderId: '547375660208',
    projectId: 'flutter-maps-2408',
    storageBucket: 'flutter-maps-2408.firebasestorage.app',
    iosBundleId: 'com.example.flutterMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX_cVDWMqirYC276hPhrp3zYCqwXgCrzo',
    appId: '1:547375660208:ios:4cd72b05210f6ba4890f75',
    messagingSenderId: '547375660208',
    projectId: 'flutter-maps-2408',
    storageBucket: 'flutter-maps-2408.firebasestorage.app',
    iosBundleId: 'com.example.flutterMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTXx4vic-brNpnc3g2MVZ9MI9U1r6QT4A',
    appId: '1:547375660208:web:5bad66480be7b7e9890f75',
    messagingSenderId: '547375660208',
    projectId: 'flutter-maps-2408',
    authDomain: 'flutter-maps-2408.firebaseapp.com',
    storageBucket: 'flutter-maps-2408.firebasestorage.app',
    measurementId: 'G-NM9LMQXXKD',
  );
}
